table Discount_dimension
	lineageTag: 622421ab-edc1-4e74-8296-7e124d7ff6d4

	column 'Discount Band'
		dataType: string
		lineageTag: 44d11930-ac5f-46eb-8838-c28553cb1d62
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Discount Brand Key'
		dataType: int64
		formatString: 0
		lineageTag: 0fa58bab-53dd-4a6d-a3a3-2a71f677d850
		summarizeBy: none
		sourceColumn: Discount Brand Key

		annotation SummarizationSetBy = Automatic

	partition Discount_dimension = m
		mode: import
		queryGroup: 'Dimension Table'
		source =
				let
				    Source = financials,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Discount Band"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Discount Brand Key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

